export const MOCK_NOTIFICATIONS = [
    {
        id: '1',
        avatarUrl: 'https://github.com/diego3g.png',
        title: 'Diego Fernandes',
        description: 'curtiu sua publicação sobre React Native.',
        date: '2 min atrás',
        isRead: false,
    },
    {
        id: '2',
        avatarUrl: 'https://github.com/maykbrito.png',
        title: 'Mayk Brito',
        description: 'comentou no seu post: "Excelente conteúdo!"',
        date: '1 hora atrás',
        isRead: false,
    },
    {
        id: '3',
        avatarUrl: 'https://github.com/jakeliny.png',
        title: 'Jakeliny Gracielly',
        description: 'começou a seguir você.',
        date: '3 horas atrás',
        isRead: true,
    },
    {
        id: '4',
        avatarUrl: 'https://github.com/rodrigorgtic.png',
        title: 'Rodrigo Gonçalves',
        description: 'compartilhou seu artigo sobre Expo Router.',
        date: 'Ontem',
        isRead: true,
    },
    {
        id: '5',
        avatarUrl: 'https://github.com/filipedeschamps.png',
        title: 'Filipe Deschamps',
        description: 'mencionou você em um comentário.',
        date: '2 dias atrás',
        isRead: true,
    },
    {
        id: '6',
        avatarUrl: 'https://github.com/diego3g.png',
        title: 'Diego Fernandes',
        description: 'publicou um novo vídeo: "O futuro do React Native".',
        date: '3 dias atrás',
        isRead: true,
    },
    {
        id: '7',
        avatarUrl: 'https://github.com/maykbrito.png',
        title: 'Mayk Brito',
        description: 'convidou você para o grupo "Discover".',
        date: '1 semana atrás',
        isRead: true,
    },
];
